name: Metrics
on:
  # Schedule daily updates
  schedule: [{cron: "0 0 * * *"}]
  # (optional) Run workflow manually
  workflow_dispatch:
  # (optional) Run workflow when pushing on master/main
  push: {branches: ["master", "main"]}
jobs:
  github-metrics:
    runs-on: ubuntu-latest
    steps:
      - uses: lowlighter/metrics@latest
        with:
          token: ${{ secrets.METRICS_TOKEN }}
          user: welps
          template: classic
          base:
          config_timezone: America/New_York
          plugin_anilist: true
          plugin_anilist_medias: manga
          plugin_anilist_user: welps
          plugin_anilist_sections: favorites, reading, characters
          plugin_anilist_limit: 20
